bind 0.0.0.0
port 6379
protected-mode yes

# Auth configurata da entrypoint tramite variabile REDIS_PASSWORD

dir /data
dbfilename dump.rdb

save 60 1000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

appendonly no

maxmemory 2gb
maxmemory-policy allkeys-lru

tcp-keepalive 300
timeout 0
loglevel notice
